---
# tasks file for tower
  - name: Install & enable EPEL repo
    yum:
      name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
    ignore_errors: true
    when: not disconnected

  - name: Install Ansible
    yum:
      name: ansible
      state: present

  - name: Make temp directory
    file:
      path: /temp
      state: directory
      mode: 0755

  - name: Download latest Ansible setup
    get_url:
      url: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
      dest: /temp/ansible.tar.gz
      mode: 0755
    when: not disconnected

  - name: copy latest Ansible bundle for disconnected install
    copy:
      src: /repos/ansible-tower-setup-bundle-latest.el7.tar.gz
      dest: /temp/ansible.tar.gz
      mode: 0755
    when: disconnected

  - name: extract Ansible tar
    unarchive:
      src: /temp/ansible.tar.gz
      dest: /temp/
      remote_src: yes

  - name: move the extracted directory
    shell : ' mv /temp/ansible-tower-setup-* /temp/ansible'
  - name: template out the tower inventory
    template:
      src: inventory.j2
      dest: /temp/ansible/inventory
      owner: root
      group: root
      mode: 0644

  - name: Install tower
    shell: /temp/ansible/setup.sh
